# Generated by Django 6.0.3 on 2026-04-27 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, unique=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
            ],
            options={
                'db_table': 'categoria',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32)),
                ('altura', models.CharField(blank=True, max_length=10, null=True)),
                ('tostion', models.CharField(blank=True, max_length=10, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.IntegerField(default=0)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=60, null=True, unique=True)),
                ('categoria', models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='catalogo.categoria')),
            ],
            options={
                'db_table': 'producto',
                'ordering': ['nombre'],
            },
        ),
    ]
