# Generated by Django 6.0.3 on 2026-05-07 14:03

import django.db.models.deletion
from django.db import migrations, models


def crear_inventario_inicial(apps, schema_editor):
    Producto = apps.get_model('catalogo', 'Producto')
    InventarioProducto = apps.get_model('catalogo', 'InventarioProducto')

    inventarios = [
        InventarioProducto(
            producto_id=producto.pk,
            stock=producto.stock,
            stock_minimo=producto.stock_minimo,
        )
        for producto in Producto.objects.all()
    ]
    InventarioProducto.objects.bulk_create(inventarios, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_producto_stock_producto_stock_minimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioProducto',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=5)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.OneToOneField(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='catalogo.producto')),
            ],
            options={
                'db_table': 'inventario_producto',
                'ordering': ['producto__nombre'],
            },
        ),
        migrations.RunPython(crear_inventario_inicial, migrations.RunPython.noop),
    ]
