# Generated by Django 6.0.3 on 2026-04-27 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(default='borrador', max_length=20)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='cuentas.usuario')),
            ],
            options={
                'db_table': 'pedido',
                'ordering': ['-id_pedido'],
            },
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id_linea', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.IntegerField(blank=True, null=True)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='lineas_pedido', to='catalogo.producto')),
                ('pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='pedidos.pedido')),
            ],
            options={
                'db_table': 'producto_pedido',
                'constraints': [models.UniqueConstraint(fields=('producto', 'pedido'), name='uq_producto_pedido')],
            },
        ),
    ]
