# Generated by Django 6.0.3 on 2026-04-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32)),
                ('apellido', models.CharField(blank=True, max_length=32, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(max_length=32)),
                ('password', models.CharField(db_column='contraseña', max_length=255)),
                ('rol', models.CharField(default='cliente', max_length=20)),
            ],
            options={
                'db_table': 'usuario',
                'ordering': ['id_usuario'],
            },
        ),
    ]
