# Generated by Django 6.0.3 on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_usuario_google_id_alter_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='usuarios/'),
        ),
    ]
