# Generated by Django 6.0.3 on 2026-06-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0004_alter_usuario_correo"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="tutorial_visto",
            field=models.BooleanField(default=False),
        ),
    ]
